version: "3.0"

services:
  app:
    container_name: python-app
    build: ./docker/python
    #image: python:3.7
    ports:
      - "5000:5000"
    volumes:
      - "./:/var/www/html"
    working_dir: "/var/www/html"
    #depends_on:
    #  - redis
    #links:
    #  - redis
  redis:
    image: redis:latest
